spring:
  profiles:
    active: dev, dev-secret
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
---
# 개발 환경 설정 파일
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: create-drop
---
# 배포 환경 설정 파일
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**