spring:
  profiles:
    active: dev, dev-secret
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

springdoc:
  swagger-ui:
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /v1/**

---
# 개발 환경 설정 파일
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
---
# 배포 환경 설정 파일
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: update
