#2023-08-30 12:40 security.jwt.token 설정
# test를 위해서, 임의로 만든 값입니다.

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: test
            client-secret: test
            redirect-uri : test
            scope: test

security :
  jwt :
    token:
      secret-key: tttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttt
      expire-length : 10000000000000

crawling:
  server :
    post:
      api:
        endPoint: test

login:
  redirect:
    url: "test"